meta_product_name: "Wasteless"
meta_title: "Wasteless - Revolutionize Your Approach to Waste: Introducing Wasteless - The Future of Sustainable Living"
meta_description: "Discover Wasteless, a groundbreaking solution that transforms the way we handle waste. Embrace sustainability and reduce environmental impact with our innovative approach. Join the movement towards a waste-free future today!"
meta_image: "logo-green-og.png" # should exist in `app/assets/images/`
